"""Translate the WorkloadHub PostgreSQL dump into the two schema files the Java module ships.

Usage: python3 server/tools/translate-schema.py path/to/schema.sql
Writes server/forecast-core/src/main/resources/schema/workloadhub-postgresql.sql (the dump without
psql directives, SET lines and OWNER statements) and workloadhub-sqlite.sql (uuid, varchar, text,
date, time, timestamp -> TEXT; double precision -> REAL; bigint, integer, boolean -> INTEGER;
same names, keys, foreign keys and CHECK lists). Run it again whenever the owner's schema changes
and commit both outputs; SchemaFilesTest keeps them in step.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "forecast-core/src/main/resources/schema"


def sqlite_type(pg_type: str) -> str:
    t = pg_type.strip()
    if t.startswith(("uuid", "character varying", "text", "time", "date")):
        return "TEXT"
    if t.startswith("double precision"):
        return "REAL"
    if t.startswith(("bigint", "integer", "boolean")):
        return "INTEGER"
    raise SystemExit(f"unknown PostgreSQL type: {t}")


def clean_postgresql(src: str) -> str:
    kept = []
    for line in src.splitlines():
        if line.startswith(("\\restrict", "\\unrestrict", "SET ", "SELECT pg_catalog")):
            continue
        if re.match(r"^ALTER (TABLE|SCHEMA) .* OWNER TO postgres;$", line):
            continue
        if line.startswith(("-- TOC", "-- Dumped", "-- Started", "-- Completed")):
            continue
        kept.append(line)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(kept)).strip() + "\n"


def translate_sqlite(src: str) -> str:
    tables = re.findall(r"CREATE TABLE task_service\.(\w+) \((.*?)\n\);", src, re.S)
    pks: dict[str, str] = {}
    uniques: dict[str, set[str]] = {}
    fks: dict[str, list[tuple[str, str, str]]] = {}
    pattern = (
        r"ALTER TABLE ONLY task_service\.(\w+)\n\s+ADD CONSTRAINT (\w+) (PRIMARY KEY|UNIQUE|FOREIGN KEY)"
        r" \(([^)]+)\)(?: REFERENCES task_service\.(\w+)\(([^)]+)\))?;"
    )
    for m in re.finditer(pattern, src):
        table, _name, kind, cols, ref_table, ref_cols = m.groups()
        if kind == "PRIMARY KEY":
            pks[table] = cols
        elif kind == "UNIQUE":
            uniques.setdefault(table, set()).add(cols)
        else:
            fks.setdefault(table, []).append((cols, ref_table, ref_cols))
    out = [
        "-- WorkloadHub schema (task_service, PostgreSQL 18 dump of 2026-09-09) translated to SQLite.",
        "-- uuid, varchar, text, date, time and timestamp -> TEXT (ISO 8601); double precision -> REAL;",
        "-- bigint, integer and boolean -> INTEGER (booleans 0/1). Names, keys and foreign keys unchanged.",
        "-- Regenerated by server/tools/translate-schema.py; do not edit by hand.",
        "",
    ]
    for table, body in tables:
        cols: list[str] = []
        checks: list[str] = []
        for raw in body.split("\n"):
            raw = raw.strip().rstrip(",")
            if not raw:
                continue
            if raw.startswith("CONSTRAINT"):
                m = re.match(
                    r"CONSTRAINT \w+ CHECK \(\(\((\w+)\)::text = ANY \(\(ARRAY\[(.*?)\]\)::text\[\]\)\)\)", raw
                )
                if m:
                    values = ", ".join(f"'{v}'" for v in re.findall(r"'([^']+)'", m.group(2)))
                    checks.append(f"CHECK ({m.group(1)} IN ({values}))")
                continue
            m = re.match(r"(\w+) (.+?)( DEFAULT [^ ]+)?( NOT NULL)?$", raw)
            assert m, raw
            name, pg_type, default, not_null = m.groups()
            default_sql = ""
            if default:
                value = default.split(" ", 2)[2]
                value = {"false": "0", "true": "1"}.get(value, value)
                default_sql = f" DEFAULT {value}"
            cols.append(f"    {name} {sqlite_type(pg_type)}{default_sql}{not_null or ''}")
        if table in pks:
            cols.append(f"    PRIMARY KEY ({pks[table]})")
        for u in sorted(uniques.get(table, ())):
            cols.append(f"    UNIQUE ({u})")
        for c, ref_table, ref_cols in fks.get(table, []):
            cols.append(f"    FOREIGN KEY ({c}) REFERENCES {ref_table}({ref_cols})")
        cols += [f"    {c}" for c in checks]
        out.append(f"CREATE TABLE {table} (\n" + ",\n".join(cols) + "\n);\n")
    return "\n".join(out)


def main() -> None:
    src = Path(sys.argv[1]).read_text(encoding="utf-8")
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "workloadhub-postgresql.sql").write_text(clean_postgresql(src), encoding="utf-8")
    (OUT / "workloadhub-sqlite.sql").write_text(translate_sqlite(src), encoding="utf-8")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
