package com.workloadhub.forecast.tools.seed;

import com.workloadhub.forecast.tools.export.ExportEnvelope;
import com.workloadhub.forecast.tools.export.WorkloadHubSchema;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.UUID;

/** Orchestrates the seed: directory, calendar, absences, projects, rhythm, work queue, envelope. */
public final class SeedGenerator {

    private SeedGenerator() {
    }

    /** The tables a real-mode seed writes: the application's own database already holds every other one (design 2026-09-17, section 7). */
    public static final List<String> REAL_MODE_TABLES = List.of("projects", "tasks", "task_history", "time_logs", "personal_leaves");

    /**
     * The seed forecast-core's tests read (36 users, 30 weeks, seed 11, last day 2026-09-06), committed as
     * forecast-core/src/test/resources/fixtures/seeded-rows.sql and regenerated by `experiment.sh fixture`.
     * FixtureFreshnessTest fails the gate when the committed file no longer matches this generator.
     */
    public static final SeedConfig FIXTURE = new SeedConfig(30, java.time.LocalDate.of(2026, 9, 6), 11, true, 36);

    /** Free-text columns a carried-over row may embed a real identity in; never an id, key, status or date column. */
    private static final Set<String> SCRUBBABLE_COLUMNS = Set.of("name", "description", "title", "note");

    /**
     * The scrub map's keys, sorted longest first so a name that is a literal prefix of another (e.g.
     * "Amina" inside "Aminata") cannot consume part of the longer name before the longer name's own
     * entry gets a chance to match the whole thing; equal-length keys break ties by the key string
     * itself, for a total order and so applying them is deterministic regardless of map iteration order.
     * Blank keys are dropped: {@code "".replace("", x)} would otherwise splice x between every character
     * of every string. Computed once per {@link #generate} call, not per row.
     */
    private static List<Map.Entry<String, String>> sortedScrubKeys(Map<String, String> identityScrub) {
        List<Map.Entry<String, String>> byLengthDesc = new ArrayList<>(identityScrub.entrySet());
        byLengthDesc.removeIf(e -> e.getKey() == null || e.getKey().isBlank());
        byLengthDesc.sort(Comparator.<Map.Entry<String, String>>comparingInt(e -> e.getKey().length()).reversed()
                .thenComparing(Map.Entry::getKey));
        return byLengthDesc;
    }

    /**
     * Replaces every occurrence of a scrubbed identity's original text with its replacement, in place,
     * in {@code row}'s {@link #SCRUBBABLE_COLUMNS} only: an id, a foreign key, a key, a status or a date
     * must never be touched, since a coincidental substring match there would corrupt a value the rest of
     * the pipeline parses (a UUID, an ISO date) rather than merely reword free text.
     */
    private static void scrubIdentities(LinkedHashMap<String, Object> row, List<Map.Entry<String, String>> byLengthDesc) {
        if (byLengthDesc.isEmpty()) {
            return;
        }
        for (Map.Entry<String, Object> e : row.entrySet()) {
            if (!SCRUBBABLE_COLUMNS.contains(e.getKey())) {
                continue;
            }
            if (e.getValue() instanceof String s) {
                String scrubbed = s;
                for (Map.Entry<String, String> r : byLengthDesc) {
                    scrubbed = scrubbed.replace(r.getKey(), r.getValue());
                }
                if (!scrubbed.equals(s)) {
                    e.setValue(scrubbed);
                }
            }
        }
    }

    /** Guards {@link #scrubIdentities} never corrupted an id or foreign key column of {@code row}. */
    private static void assertIdsAreUuids(String table, LinkedHashMap<String, Object> row) {
        for (Map.Entry<String, Object> e : row.entrySet()) {
            String column = e.getKey();
            if (!column.equals("id") && !column.endsWith("_id")) {
                continue;
            }
            Object value = e.getValue();
            if (value == null) {
                continue;
            }
            try {
                UUID.fromString(String.valueOf(value));
            } catch (IllegalArgumentException ex) {
                throw new IllegalStateException(
                        "Identity scrub corrupted " + table + "." + column + " = " + value, ex);
            }
        }
    }

    /** Non-blank original identity fields of {@code original}, mapped to the same fields of {@code replacement}. */
    private static void addIdentityScrub(Map<String, String> identityScrub, LinkedHashMap<String, Object> original,
            LinkedHashMap<String, Object> replacement) {
        for (String field : List.of("full_name", "email", "username", "account_name")) {
            Object oldValue = original.get(field);
            if (oldValue instanceof String s && !s.isBlank()) {
                identityScrub.put(s, (String) replacement.get(field));
            }
        }
    }

    public static ExportEnvelope generate(ExportEnvelope input, SeedConfig cfg) {
        SeedRandom rnd = new SeedRandom(cfg.seed());
        boolean synthetic = cfg.synthetic();
        if (input == null && !synthetic) {
            throw new IllegalArgumentException("Real mode needs an input export");
        }

        // 1. source rows
        List<LinkedHashMap<String, Object>> users;
        List<LinkedHashMap<String, Object>> teams;
        List<LinkedHashMap<String, Object>> members;
        List<LinkedHashMap<String, Object>> projectRows;
        List<LinkedHashMap<String, Object>> statuses;
        List<LinkedHashMap<String, Object>> types;
        List<LinkedHashMap<String, Object>> roles;
        List<LinkedHashMap<String, Object>> holidays;
        List<LinkedHashMap<String, Object>> jobTitles;
        List<LinkedHashMap<String, Object>> syncMetadata;
        // every non-blank full_name/email/username/account_name of every input user (kept or not,
        // built before shrink) mapped to its anonymised replacement, for scrubbing free text carried
        // over unmodified from the input; empty (and unused) outside synthetic-mode-with-real-input.
        Map<String, String> identityScrub = new HashMap<>();
        if (input != null) {
            users = input.rows("users");
            teams = input.rows("teams");
            members = input.rows("team_members");
            projectRows = input.rows("projects");
            statuses = input.rows("task_statuses");
            types = input.rows("task_types");
            roles = input.rows("user_roles");
            holidays = input.rows("holidays");
            jobTitles = input.rows("job_titles");
            syncMetadata = input.rows("sync_metadata");
            if (synthetic) {
                // anonymise every input user first (not just the kept ones), so a person's original
                // identity can be scrubbed from carried-over free text even when they get shrunk out
                // of the users table entirely; shrink afterwards to select who is actually kept. The
                // fields shrink sorts and filters on (department, manager_id, id) are untouched by
                // anonymise, so which users end up kept is the same either order.
                List<LinkedHashMap<String, Object>> anonymisedAll = Anonymiser.anonymise(users, rnd);
                for (int i = 0; i < users.size(); i++) {
                    addIdentityScrub(identityScrub, users.get(i), anonymisedAll.get(i));
                }
                users = Anonymiser.shrink(anonymisedAll, cfg.users());
                // operator usernames with no forecast value; never carried into a synthetic export
                syncMetadata = List.of();
            }
            if (!Reference.covers(statuses, types)) {
                if (!synthetic) {
                    // Real mode writes neither task_statuses nor task_types (design 2026-09-17, section 7.1), so a
                    // substitute would point every task at rows the database does not have: refuse instead. A real
                    // export always carries them all, because the application defines them.
                    throw new IllegalArgumentException("real mode needs an export that carries every task status and type the seed writes: "
                            + Reference.missing(statuses, types));
                }
                // a partial export in synthetic mode (tests, early installs): the synthetic envelope writes both tables itself
                statuses = ReferenceData.statusRows();
                types = ReferenceData.typeRows();
            }
        } else {
            users = ReferenceData.syntheticUsers(cfg.users() > 0 ? cfg.users() : 40, rnd);
            teams = List.of();
            members = List.of();
            projectRows = List.of();
            statuses = ReferenceData.statusRows();
            types = ReferenceData.typeRows();
            roles = ReferenceData.roleRows();
            holidays = ReferenceData.holidayRows(cfg.firstMonday().getYear(), cfg.lastDay().getYear());
            TreeSet<String> titles = new TreeSet<>();
            for (LinkedHashMap<String, Object> u : users) {
                if (u.get("job_title") != null) {
                    titles.add((String) u.get("job_title"));
                }
            }
            jobTitles = ReferenceData.jobTitleRows(titles);
            syncMetadata = List.of();
        }
        if (synthetic) {
            // keep only the kept users' memberships
            java.util.Set<Object> ids = new java.util.HashSet<>();
            users.forEach(u -> ids.add(u.get("id")));
            members = members.stream().filter(m -> ids.contains(m.get("user_id"))).toList();
            // real identities can be embedded in free text carried over from the input (a team name
            // built as "<dept> · <manager's full name>", say): scrub every kept and dropped input
            // user's original identity, wherever it appears in the rows kept from the input, with its
            // anonymised replacement, so no leftover string in the export can identify anyone.
            List<Map.Entry<String, String>> scrubKeys = sortedScrubKeys(identityScrub);
            teams = teams.stream().map(t -> {
                LinkedHashMap<String, Object> row = new LinkedHashMap<>(t);
                if (row.get("manager_id") != null && !ids.contains(row.get("manager_id"))) {
                    row.put("manager_id", null);
                }
                scrubIdentities(row, scrubKeys);
                assertIdsAreUuids("teams", row);
                return row;
            }).toList();
            projectRows = projectRows.stream()
                    .filter(p -> p.get("owner_id") == null || ids.contains(p.get("owner_id")))
                    .map(p -> {
                        LinkedHashMap<String, Object> row = new LinkedHashMap<>(p);
                        scrubIdentities(row, scrubKeys);
                        assertIdsAreUuids("projects", row);
                        return row;
                    })
                    .toList();
        }

        // 2. structure
        Directory.Result dir = Directory.derive(users, cfg, rnd);
        Map<UUID, Person> people = new HashMap<>();
        for (Person p : dir.people()) {
            people.put(p.id(), p);
        }
        SeedCalendar cal = SeedCalendar.fromHolidayRows(holidays, cfg);

        // 3. absences, in id order for determinism
        List<Person> ordered = new ArrayList<>(dir.people());
        ordered.sort(Comparator.comparing(p -> p.id().toString()));
        Map<UUID, AbsencePlanner.Plan> plans = new HashMap<>();
        List<LinkedHashMap<String, Object>> leaves = new ArrayList<>();
        for (Person p : ordered) {
            AbsencePlanner.Plan plan = AbsencePlanner.plan(p, cal, cfg, rnd);
            plans.put(p.id(), plan);
            if (p.counted()) {
                leaves.addAll(plan.leaveRows());
            }
        }

        // 4. projects, rhythm, work
        List<Project> projects = ProjectPlanner.plan(dir.departments(), people, projectRows, cfg, rnd);
        Rhythm rhythm = new Rhythm(cfg, cal, people, plans, rnd);
        Reference ref = Reference.from(statuses, types);
        WorkQueue.Result work = WorkQueue.run(cfg, cal, dir.people(), plans, projects, rhythm, ref,
                WorkQueue.Rates.DEFAULT, rnd);

        // 4b. the project teams: one per project this generator invented, holding whoever took its work. The
        // application's `teams` table means exactly that, so it is derived from the work rather than declared
        // in front of it (design 2026-09-21, ruling 10). A project an export carried keeps its own team.
        Set<String> carriedOver = new HashSet<>();
        projectRows.forEach(r -> carriedOver.add(String.valueOf(r.get("id"))));
        List<Project> minted = projects.stream().filter(pr -> !carriedOver.contains(pr.id().toString())).toList();
        Set<String> usedTeamNames = new HashSet<>();
        teams.forEach(t -> {
            if (t.get("name") instanceof String n) {
                usedTeamNames.add(n);
            }
        });
        ProjectPlanner.ProjectTeams projectTeams = ProjectPlanner.projectTeams(minted, work.taskRows(), usedTeamNames, cfg, rnd);
        List<LinkedHashMap<String, Object>> outTeams = new ArrayList<>(teams);
        outTeams.addAll(projectTeams.teamRows());
        List<LinkedHashMap<String, Object>> outMembers = new ArrayList<>(members);
        outMembers.addAll(projectTeams.memberRows());

        // 5. project rows with the next task number
        Map<String, LinkedHashMap<String, Object>> existingById = new HashMap<>();
        for (LinkedHashMap<String, Object> r : projectRows) {
            existingById.put((String) r.get("id"), r);
        }
        List<LinkedHashMap<String, Object>> outProjects = new ArrayList<>();
        List<Project> sortedProjects = new ArrayList<>(projects);
        sortedProjects.sort(Comparator.comparing(Project::key));
        for (Project p : sortedProjects) {
            outProjects.add(ProjectPlanner.row(p, existingById.get(p.id().toString()), work.nextTaskNumber().getOrDefault(p.id(), 1L), cfg));
        }

        // 6. envelope in table order: every table in synthetic mode (the experiment database is built from it),
        // the five work tables in real mode (the application's database holds the rest)
        LinkedHashMap<String, List<LinkedHashMap<String, Object>>> data = new LinkedHashMap<>();
        List<String> excluded;
        if (synthetic) {
            for (String table : WorkloadHubSchema.TABLE_ORDER) {
                data.put(table, new ArrayList<>());
            }
            data.put("user_roles", roles);
            data.put("job_titles", jobTitles);
            data.put("users", dir.userRows());
            data.put("teams", outTeams);
            data.put("team_members", outMembers);
            data.put("task_statuses", statuses);
            data.put("task_types", types);
            data.put("holidays", cal.holidayRows());
            data.put("sync_metadata", syncMetadata);
            excluded = List.of("refresh_tokens");
        } else {
            excluded = new ArrayList<>();
            for (String table : WorkloadHubSchema.TABLE_ORDER) {
                if (REAL_MODE_TABLES.contains(table)) {
                    data.put(table, new ArrayList<>());
                } else {
                    excluded.add(table);
                }
            }
        }
        data.put("projects", outProjects);
        data.put("tasks", work.taskRows());
        data.put("task_history", work.historyRows());
        data.put("time_logs", work.timeLogRows());
        data.put("personal_leaves", leaves);
        String database = input == null ? "synthetic" : input.database();
        return new ExportEnvelope(database, "task_service", cfg.lastDay().atTime(18, 0).toString(), excluded, data);
    }
}
