-- WorkloadHub schema (task_service, PostgreSQL 18 dump of 2026-09-09) translated to SQLite.
-- uuid, varchar, text, date, time and timestamp -> TEXT (ISO 8601); double precision -> REAL;
-- bigint, integer and boolean -> INTEGER (booleans 0/1). Names, keys and foreign keys unchanged.
-- Regenerated by server/tools/translate-schema.py; do not edit by hand.

CREATE TABLE absences (
    date TEXT NOT NULL,
    hours REAL NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    type TEXT NOT NULL,
    note TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    CHECK (type IN ('VACATION', 'SICK_LEAVE', 'PUBLIC_HOLIDAY', 'OTHER'))
);

CREATE TABLE holidays (
    active INTEGER NOT NULL,
    end_date TEXT NOT NULL,
    start_date TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    country_code TEXT NOT NULL,
    status TEXT NOT NULL,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (title, start_date, end_date, country_code),
    CHECK (status IN ('CONFIRMED', 'PENDING')),
    CHECK (type IN ('NATIONAL', 'RELIGIOUS'))
);

CREATE TABLE job_title_role_mappings (
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    job_title_id TEXT NOT NULL,
    role_id TEXT NOT NULL,
    user_id TEXT,
    PRIMARY KEY (id),
    UNIQUE (job_title_id, user_id),
    FOREIGN KEY (job_title_id) REFERENCES job_titles(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES user_roles(id)
);

CREATE TABLE job_titles (
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (value)
);

CREATE TABLE notifications (
    is_read INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    reporter_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    type TEXT NOT NULL,
    message TEXT NOT NULL,
    metadata TEXT,
    PRIMARY KEY (id),
    CHECK (type IN ('TASK_ASSIGNED', 'TASK_STATUS_CHANGED', 'TASK_COMMENT_ADDED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'WEEK_OVERLOADED', 'TEAM_MEMBER_ADDED', 'TEAM_MEMBER_REMOVED', 'TASK_UNBLOCKED'))
);

CREATE TABLE personal_leaves (
    absence_hours REAL,
    begin_time TEXT,
    end_date TEXT NOT NULL,
    end_time TEXT,
    start_date TEXT NOT NULL,
    created_at TEXT,
    updated_at TEXT,
    employee_id TEXT NOT NULL,
    id TEXT NOT NULL,
    note TEXT,
    leave_type TEXT,
    processor TEXT,
    status TEXT,
    PRIMARY KEY (id),
    CHECK (leave_type IN ('PAID_LEAVE', 'VACATION_ADDITIONAL_DAY', 'SICK_LEAVE', 'WORK_ACCIDENT', 'JOB_SEARCH', 'FAMILY_EVENT', 'UNPAID_LEAVE')),
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE project_history (
    changed_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    changed_by TEXT NOT NULL,
    id TEXT NOT NULL,
    project_id TEXT,
    project_key TEXT,
    field_name TEXT NOT NULL,
    new_value TEXT,
    old_value TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (changed_by) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE projects (
    archived INTEGER DEFAULT 0 NOT NULL,
    archived_at TEXT,
    created_at TEXT NOT NULL,
    next_task_number INTEGER DEFAULT 1 NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER,
    archived_by TEXT,
    id TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    team_id TEXT,
    key TEXT NOT NULL,
    previous_status TEXT,
    status TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (id),
    UNIQUE (key),
    FOREIGN KEY (team_id) REFERENCES teams(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    CHECK (previous_status IN ('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED')),
    CHECK (status IN ('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED'))
);

CREATE TABLE refresh_tokens (
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    token TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (token),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE role_change_requests (
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    status TEXT NOT NULL,
    current_user_role TEXT NOT NULL,
    requested_role TEXT NOT NULL,
    job_title TEXT,
    reviewed_by TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    CHECK (current_user_role IN ('ADMIN', 'CENTER_MANAGER', 'SKILL_TEAM_LEADER', 'TEAM_LEADER', 'MEMBER', 'VIEWER')),
    CHECK (requested_role IN ('ADMIN', 'CENTER_MANAGER', 'SKILL_TEAM_LEADER', 'TEAM_LEADER', 'MEMBER', 'VIEWER')),
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE sync_metadata (
    sync_in_progress INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    last_sync_at TEXT,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    synced_by TEXT,
    last_sync_result TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE task_attachments (
    created_at TEXT NOT NULL,
    file_size INTEGER NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    uploaded_by TEXT NOT NULL,
    content_type TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    original_file_name TEXT NOT NULL,
    stored_file_name TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (stored_file_name),
    FOREIGN KEY (task_id) REFERENCES tasks(id),
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE task_comments (
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER,
    id TEXT NOT NULL,
    parent_comment_id TEXT,
    task_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    content TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_comment_id) REFERENCES task_comments(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (task_id) REFERENCES tasks(id)
);

CREATE TABLE task_history (
    changed_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    field_name TEXT NOT NULL,
    new_value TEXT,
    old_value TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (task_id) REFERENCES tasks(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE task_statuses (
    active INTEGER NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    category TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (id),
    UNIQUE (name),
    CHECK (category IN ('TO_DO', 'IN_PROGRESS', 'DONE'))
);

CREATE TABLE task_types (
    active INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    subtask_type_id TEXT,
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    PRIMARY KEY (id),
    UNIQUE (name),
    FOREIGN KEY (subtask_type_id) REFERENCES task_types(id)
);

CREATE TABLE tasks (
    archived INTEGER NOT NULL,
    due_date TEXT,
    original_estimate_hrs REAL,
    planned_week TEXT,
    remaining_estimate_hrs REAL,
    reopened_from_done INTEGER DEFAULT 0 NOT NULL,
    archived_at TEXT,
    created_at TEXT NOT NULL,
    created_date TEXT NOT NULL,
    finished_date TEXT,
    last_reopened_at TEXT,
    started_date TEXT,
    task_number INTEGER,
    updated_at TEXT NOT NULL,
    version INTEGER,
    assignee_id TEXT,
    id TEXT NOT NULL,
    parent_task_id TEXT,
    project_id TEXT NOT NULL,
    reporter_id TEXT NOT NULL,
    task_status_id TEXT NOT NULL,
    task_type_id TEXT NOT NULL,
    priority TEXT NOT NULL,
    key TEXT NOT NULL,
    description TEXT,
    title TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (key),
    FOREIGN KEY (parent_task_id) REFERENCES tasks(id),
    FOREIGN KEY (task_status_id) REFERENCES task_statuses(id),
    FOREIGN KEY (reporter_id) REFERENCES users(id),
    FOREIGN KEY (assignee_id) REFERENCES users(id),
    FOREIGN KEY (task_type_id) REFERENCES task_types(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    CHECK (priority IN ('HIGHEST', 'HIGH', 'MEDIUM', 'LOW', 'LOWEST'))
);

CREATE TABLE team_capacity (
    allocated_hrs REAL NOT NULL,
    total_capacity_hrs REAL NOT NULL,
    week_start TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    team_id TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (team_id, week_start),
    FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE team_members (
    created_at TEXT NOT NULL,
    joined_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    team_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (team_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE teams (
    active INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    version INTEGER,
    id TEXT NOT NULL,
    manager_id TEXT,
    parent_team_id TEXT,
    name TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name),
    FOREIGN KEY (parent_team_id) REFERENCES teams(id),
    FOREIGN KEY (manager_id) REFERENCES users(id)
);

CREATE TABLE time_logs (
    hours REAL NOT NULL,
    log_date TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    note TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (task_id) REFERENCES tasks(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_capacity (
    absence_hrs REAL NOT NULL,
    available_hrs REAL NOT NULL,
    base_capacity_hrs REAL NOT NULL,
    week_start TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (user_id, week_start),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_roles (
    active INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    id TEXT NOT NULL,
    code TEXT NOT NULL,
    label TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (code)
);

CREATE TABLE users (
    active INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    deactivated_at TEXT,
    updated_at TEXT NOT NULL,
    version INTEGER,
    id TEXT NOT NULL,
    manager_id TEXT,
    manager_object_id TEXT,
    object_id TEXT,
    role TEXT NOT NULL,
    account_name TEXT,
    username TEXT NOT NULL,
    department TEXT,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL,
    job_title TEXT,
    password TEXT,
    PRIMARY KEY (id),
    UNIQUE (account_name),
    UNIQUE (email),
    UNIQUE (object_id),
    UNIQUE (username),
    FOREIGN KEY (manager_id) REFERENCES users(id),
    CHECK (role IN ('ADMIN', 'CENTER_MANAGER', 'SKILL_TEAM_LEADER', 'TEAM_LEADER', 'MEMBER', 'VIEWER'))
);
